<a href="https://colab.research.google.com/github/Veroberg/br-python-condensed/blob/main/C%C3%B3pia_de_C%C3%B3pia_de_python_exercises_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://i.imgur.com/YX6UATs.png)


### **Exercícios de Python - 3** 





1 - Classe Bola:\
Crie uma classe que modele uma bola:

Atributos: Cor, material\
Métodos: trocaCor 

In [ ]:
class Ball:
    def __init__(self, color="unknown", material="unknown"):
        self.color = color
        self.material = material

    def trocaCor(self):
        troca = input("Deseja mudar a cor atual {}? [s/n]".format(self.color))

        troca = troca[0].lower()

        if troca == "s":
            nova_cor = input("\n> Nova Cor: ")
            self.color = nova_cor
        else:
            print("Ok a cor continua {}".format(self.color))

def main():
    bola01 = Ball("lilás", "borracha")

    while True:
        bola01.trocaCor()

        continuar = input("Continuar? [s/n]")
        continuar = continuar[0].lower()
        if continuar == "n":
            break


main()            

Deseja mudar a cor atual lilás? [s/n]s

> Nova Cor: Rosa
Continuar? [s/n]s
Deseja mudar a cor atual Rosa? [s/n]n
Ok a cor continua Rosa
Continuar? [s/n]n


2 - Classe Quadrado: Crie uma classe que modele um quadrado:

Atributos: Tamanho do lado
Métodos: Mudar valor do Lado e calcular Área;

In [ ]:
class Square:
    def __init__(self, lado="0"):
        self.lado = lado

    @property
    def lado(self):
        return self.__lado

    @lado.setter
    def lado(self, valor):

        if valor.isdigit():
            self.__lado = valor
        else:
            print("O valor do lado é em numeros")

    
    def valorLado(self):
        print("\nO valor do lado é {} cm".format(self.__lado))
        

    def mudarLado(self):
        novoLado = input("\nMudar lado de {} cm para: ".format(self.__lado))
        self.lado = novoLado

    def calcArea(self):
        print("\nA área do quadrado é {:.2f} cm²".format(
            float(self.__lado) * float(self.__lado)))

    def __str__(self):
        return "O quadrado possui {} cm de lado e {:.2f} cm² de area".format(
            self.__lado, float(self.__lado) * float(self.__lado))


def main():
    quadradoA = Square()
    lado = input("Insira o valor do lado: ")
    quadradoA.lado = lado

    print(quadradoA)

    quadradoA.mudarLado()
    quadradoA.valorLado()
    quadradoA.calcArea()


main()

Insira o valor do lado: 6
O quadrado possui 6 cm de lado e 36.00 cm² de area

Mudar lado de 6 cm para: 8

O valor do lado é 8 cm

A área do quadrado é 64.00 cm²


3 - Classe funcionário \
Crie uma classe que crie funcionários de uma empresa.\
Atributos: Nome, Função, Salário. \
Métodos: aumento anual. O aumento anual deve ser de 10%.\
Crie dois objetos e dê um aument de 10% a um deles e um aumento de 20% ao outro.

04 - Utilizando a biblioteca Numpy, obtenha as médias, medianas e desvios padrão de altura, peso e IMC dos membros do dicionário a seguir:\
Trasforme os dicionários em um numpy array e utilize os métodos próprios dessa classe.

In [ ]:
clientes = {'Charlotte': {'altura': 1.56, 'imc': 21, 'peso': 52, 'sexo': 'F'},
 'Claudia': {'altura': 1.56, 'imc': 25, 'peso': 62, 'sexo': 'F'},
 'Jonas': {'altura': 1.56, 'imc': 21, 'peso': 52, 'sexo': 'M'},
 'Martha': {'altura': 1.98, 'imc': 19, 'peso': 76, 'sexo': 'F'},
 'Mikkel': {'altura': 1.56, 'imc': 28, 'peso': 67, 'sexo': 'M'},
 'Ulrich': {'altura': 1.92, 'imc': 22, 'peso': 80, 'sexo': 'M'}}


In [ ]:
# Desvio Padrão de altura
altura = np.array([1.56, 1.56, 1.56, 1.98, 1.56, 1.92])
np.std(altura) 

0.18466185312619385

In [ ]:
# Desvio Padrão do imc
imc = np.array([21, 25, 21, 19, 28, 22])
np.std(imc)  

2.981423969999719

In [ ]:
# Desvio Padrão de peso
peso = np.array([52, 62, 52, 76, 67, 80])
np.std(peso) 

10.77677544021814

In [ ]:
# Media da altura
altura = np.array([1.56, 1.56, 1.56, 1.98, 1.56, 1.92])
np.mean(altura)

1.6900000000000002

In [ ]:
# Media do imc
imc = np.array([21, 25, 21, 19, 28, 22])
np.mean(imc)

22.666666666666668

In [ ]:
# Media do peso
peso = np.array([52, 62, 52, 76, 67, 80])
np.mean(peso)

64.83333333333333

In [ ]:
# Mediana da altura
altura = np.array([1.56, 1.56, 1.56, 1.98, 1.56, 1.92])
np.sort(altura)

array([1.56, 1.56, 1.56, 1.56, 1.92, 1.98])

In [ ]:
# Mediana do imc
imc = np.array([21, 25, 21, 19, 28, 22])
np.sort(imc)

array([19, 21, 21, 22, 25, 28])

In [ ]:
# Mediana do peso
peso = np.array([52, 62, 52, 76, 67, 80])
np.sort(peso)

array([52, 52, 62, 67, 76, 80])

05 - Realize o mesmo procedimento com a biblioteca Statistics


In [ ]:
import statistics
import math
from scipy import stats
import numpy
from collections import Counter

In [ ]:
# Mediana da altura
altura = [1.56, 1.56, 1.56, 1.98, 1.56, 1.92]
mediana = statistics.median(altura)
print("Mediana: Altura ", mediana)

# Mediana do imc
imc = [21, 25, 21, 19, 28, 22]
mediana = statistics.median(imc)
print("Mediana: Imc ", mediana)

# Mediana do peso
peso = [52, 62, 52, 76, 67, 80]
mediana = statistics.median(peso)
print("Mediana: Peso ", mediana)


Mediana: Altura  1.56
Mediana: Imc  21.5
Mediana: Peso  64.5


In [ ]:
# Media da altura
altura = [1.56, 1.56, 1.56, 1.98, 1.56, 1.92]
media = statistics.mean(altura)
print("Média aritmética: Altura ", media)

# Media do imc
imc = [21, 25, 21, 19, 28, 22]
media = statistics.mean(imc)
print("Média aritmética: Imc ", media)

# Media do peso
peso = [52, 62, 52, 76, 67, 80]
media = statistics.mean(peso)
print("Média aritmética:Altura: Peso ", media)

Média aritmética: Altura  1.69
Média aritmética: Imc  22.666666666666668
Média aritmética:Altura: Peso  64.83333333333333
